version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/modules
      - .:/app
    stdin_open: true
  test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/modules
      - .:/app
    command: ["npm", "run", "test"]
    stdin_open: true